spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT&&characterEncoding=utf-8
    username: root
    password: 84994800
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/

logging:
  level:
    root: warn
    cn.leo.leoblog: info
  file: log/blog-dev.log